export const people = [
    {
        name: 'Václav Procházka',
        likes: '506',
        reviews: '25',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/svg/cactus.webp',
        alt: 'person1',
    },
    {
        name: 'Ondřej Efenberk',
        likes: '340',
        reviews: '20',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/svg/house.webp',
        alt: 'person2',
    },
    {
        name: 'Michaela Marková',
        likes: '400',
        reviews: '30',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/svg/rock.webp',
        alt: 'person2',
    },
    {
        name: 'Tereza Marková',
        likes: '200',
        reviews: '20',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/svg/water.webp',
        alt: 'person3',
    },
    {
        name: 'Zdeněk Kafka',
        likes: '158',
        reviews: '18',
        moto: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit,',
        src: '/svg/tree.webp',
        alt: 'person4',
    }
]

export const TestPeople = [
    {
        name: "John Doe",
        number: '01',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/tree.png",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.png',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.png',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '02',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/cactus.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.png',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.png',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '03',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/house.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.png',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.png',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '04',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
            src: "/svg/tree.png",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.png',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.png',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '05',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/rock.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.png',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.png',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '06',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/tree.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.png',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.png',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '07',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/water.webp",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.png',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.png',
        altText2: 'asset2',
    },
    {
        name: "Jane Doe",
        number: '08',
        moto: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        src: "/svg/tree.png",
        alt: "profile_pic1",
        photo1: '/assets/reviewsBackground.png',
        altText1: 'asset1',
        photo2: '/assets/reviewsBackground.png',
        altText2: 'asset2',
    },
]